version: '3.8'

services:
  php:
    container_name: telebot_php
    build:
      context: ./
      dockerfile: "docker/configs/php/Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=xdebug_telebot"
    volumes:
      - .:/srv/src/telebot

  nginx:
    container_name: telebot_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/srv/src/telebot
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: telebot_mysql
    ports:
      - "3316:3306"
    env_file:
      - ./docker/configs/mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - php

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--timeout", "0", "--maxmemory", "256mb", "--appendonly", "yes", "--save", "900 1", "--save", "300 10", "--save", "60 10000", "--maxmemory-policy", "allkeys-lru" ]
    depends_on:
      - php

volumes:
  mysql_data:
  redis-data:
