parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Telegram\ConfigBot:
    arguments:
      $token: '%env(API_TOKEN_CONFIG_BOT)%'

  App\Telegram\ParseBot:
    arguments:
      $token: '%env(API_TOKEN_PARSE_BOT)%'

  App\Command\Telegram\:
    resource: '../src/Command/Telegram/*'
    tags: [ 'telegram.command' ]

  App\Command\Telegram\Channel\AddMyChannel:
    arguments:
      $newsBotUsername: '%env(TAG_PARSE_BOT)%'
    tags: [ 'telegram.command' ]

  App\Command\Telegram\CommandHandler:
    arguments:
      $configBot: '@App\Telegram\ConfigBot'
      $commands: !tagged_iterator telegram.command
