parameters:
  telegram.api_id: '%env(TELEGRAM_API_ID)%'
  telegram.api_hash: '%env(TELEGRAM_API_HASH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Doctrine\DBAL\Logging\EchoSQLLogger:
    public: true
    tags:
      - { name: doctrine.dbal.logger, connection: default }

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Telegram\ConfigBot:
    arguments:
      $token: '%env(API_TOKEN_CONFIG_BOT)%'

  App\Telegram\ParseBot:
    arguments:
      $token: '%env(API_TOKEN_PARSE_BOT)%'

  App\Command\Telegram\:
    resource: '../src/Command/Telegram/*'
    tags: [ 'telegram.command' ]

  App\Command\Telegram\Channel\AddMyChannel:
    arguments:
      $newsBotUsername: '%env(TAG_PARSE_BOT)%'
    tags: [ 'telegram.command' ]

  App\Command\Telegram\CommandHandler:
    arguments:
      $configBot: '@App\Telegram\ConfigBot'
      $commands: !tagged_iterator telegram.command

  # Оновлення: правильний клас для MadelineProtoSettings
  App\Service\MadelineProtoSettings:
    arguments:
      $apiId: '%telegram.api_id%'
      $apiHash: '%telegram.api_hash%'

  App\Service\MadelineProto:
    factory: [ '@App\Service\MadelineProtoFactory', 'create' ]
    arguments:
      - 'session.madeline'
      - '@App\Service\MadelineProtoSettings'

  App\Service\ParseNewsService:
    arguments:
      $madelineProto: '@App\Service\MadelineProto'

