parameters:
  telegram.api_id: '%env(TELEGRAM_API_ID)%'
  telegram.api_hash: '%env(TELEGRAM_API_HASH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Doctrine\DBAL\Logging\EchoSQLLogger:
    public: true
    tags:
      - { name: doctrine.dbal.logger, connection: default }

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\Telegram\ConfigBot:
    arguments:
      $token: '%env(API_TOKEN_CONFIG_BOT)%'
      $domain: '%env(URL_PROXY_SERVER_FOR_WEBHOOK)%'
    tags: [ 'app.telegram.bot' ]

  App\Service\Telegram\ParserBot:
    arguments:
      $token: '%env(API_TOKEN_PARSER_BOT)%'
      $domain: '%env(URL_PROXY_SERVER_FOR_WEBHOOK)%'
    tags: [ 'app.telegram.bot' ]

  start_command.parser:
    class: App\Service\Telegram\Command\StartCommand
    arguments:
      $bot: '@App\Service\Telegram\ParserBot'
    tags: [ 'telegram.command' ]

  start_command.config:
    class: App\Service\Telegram\Command\StartCommand
    arguments:
      $bot: '@App\Service\Telegram\ConfigBot'
    tags: [ 'telegram.command' ]

  cancel_command.parser:
    class: App\Service\Telegram\Command\CancelCommand
    arguments:
      $bot: '@App\Service\Telegram\ParserBot'
    tags: [ 'telegram.command' ]

  cancel_command.config:
    class: App\Service\Telegram\Command\CancelCommand
    arguments:
      $bot: '@App\Service\Telegram\ConfigBot'
    tags: [ 'telegram.command' ]

  App\Service\Telegram\WebhookHandlerServiceFactory:
    arguments:
      $bots: !tagged_iterator app.telegram.bot
      $commands: !tagged_iterator telegram.command

  App\Service\MadelineProtoSettings:
    arguments:
      $apiId: '%telegram.api_id%'
      $apiHash: '%telegram.api_hash%'

  App\Service\MadelineProto:
    factory: [ '@App\Service\MadelineProtoFactory', 'create' ]
    arguments:
      - 'session.madeline'
      - '@App\Service\MadelineProtoSettings'

  # Сервис для парсинга
  App\Service\ParsePostService:
    arguments:
      $madelineProto: '@App\Service\MadelineProto'
